import { describe, it, expect } from 'vitest';
import { generateHTML } from '@/lib/code-generators/html-generator';
import type { DesignTokens } from '@/stores/workspace-store';

const mockTokens: DesignTokens = {
  colorPalette: {
    primary: '#3b82f6',
    secondary: '#8b5cf6',
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#1e293b',
    textMuted: '#64748b',
    border: '#e2e8f0',
    accent: '#f59e0b',
  },
  fonts: {
    heading: 'Inter',
    body: 'Roboto',
    mono: 'Fira Code',
    headingWeight: 700,
    bodyWeight: 400,
    headingLineHeight: 1.2,
    bodyLineHeight: 1.5,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    small: 4,
    medium: 8,
    large: 16,
  },
  shadows: {
    light: '0 1px 2px rgba(0,0,0,0.05)',
    medium: '0 4px 6px rgba(0,0,0,0.1)',
    heavy: '0 10px 15px rgba(0,0,0,0.1)',
  },
};

describe('generateHTML', () => {
  it('should generate HTML with index and components', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result).toHaveProperty('index');
    expect(result).toHaveProperty('components');
    expect(result.components).toHaveProperty('hero');
    expect(result.components).toHaveProperty('card');
    expect(result.components).toHaveProperty('button');
  });

  it('should generate valid HTML structure', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.index).toContain('<!DOCTYPE html>');
    expect(result.index).toContain('<html lang="zh-CN">');
    expect(result.index).toContain('<head>');
    expect(result.index).toContain('<body>');
    expect(result.index).toContain('</html>');
  });

  it('should include style name in title', () => {
    const result = generateHTML(mockTokens, 'My Design System');

    expect(result.index).toContain('<title>My Design System - Generated by StyleSnap</title>');
  });

  it('should link CSS files', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.index).toContain('href="styles.css"');
    expect(result.index).toContain('href="styles.module.css"');
  });

  it('should generate Hero section', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.index).toContain('<section class="hero">');
    expect(result.index).toContain('<h1 class="hero-title">');
    expect(result.index).toContain('<p class="hero-subtitle">');
    expect(result.index).toContain('<button class="button button-primary">');
  });

  it('should generate Card section', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.index).toContain('<div class="card">');
    expect(result.index).toContain('<div class="card-header">');
    expect(result.index).toContain('<h2 class="card-title">');
    expect(result.index).toContain('<p class="card-description">');
  });

  it('should generate standalone Hero component', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.components.hero).toContain('<section class="hero">');
    expect(result.components.hero).toContain('<h1 class="hero-title">Hero 标题</h1>');
  });

  it('should generate standalone Card component', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.components.card).toContain('<div class="card">');
    expect(result.components.card).toContain('<h3 class="card-title">卡片标题</h3>');
  });

  it('should generate Button components', () => {
    const result = generateHTML(mockTokens, 'Test Style');

    expect(result.components.button).toContain('<button class="button button-primary">');
    expect(result.components.button).toContain('<button class="button button-secondary">');
    expect(result.components.button).toContain('disabled');
  });
});

describe('generateHTML - Default Values', () => {
  it('should use default style name when not provided', () => {
    const result = generateHTML(mockTokens);

    expect(result.index).toContain('Design System - Generated by StyleSnap');
  });
});
