/**
 * HTML Generator - 生成 HTML 模板
 * 将 DesignTokens 转换为可用的 HTML 代码
 */

import { type DesignTokens } from '@/stores/workspace-store';

/**
 * 生成的 HTML 结果
 */
export interface GeneratedHTML {
  /** 完整 HTML 页面 */
  index: string;
  /** 可选：独立组件 */
  components: {
    hero: string;
    card: string;
    button: string;
  };
}

/**
 * 生成 HTML 模板
 * @param tokens - 设计变量
 * @param styleName - 风格名称
 * @returns 生成的 HTML 代码
 */
export function generateHTML(tokens: DesignTokens, styleName: string = 'Design System'): GeneratedHTML {
  const index = generateIndexHTML(tokens, styleName);
  const components = {
    hero: generateHeroHTML(tokens),
    card: generateCardHTML(tokens),
    button: generateButtonHTML(tokens),
  };

  return { index, components };
}

/**
 * 生成完整 HTML 页面
 */
function generateIndexHTML(tokens: DesignTokens, styleName: string): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${styleName} - Generated by StyleSnap</title>
  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="styles.module.css">
</head>
<body>
  <!-- Hero Section -->
  <section class="hero">
    <div class="container">
      <h1 class="hero-title">欢迎来到 ${styleName}</h1>
      <p class="hero-subtitle">这是一个使用 StyleSnap 生成的设计系统示例</p>
      <div class="hero-actions">
        <button class="button button-primary">开始使用</button>
        <button class="button button-secondary">了解更多</button>
      </div>
    </div>
  </section>

  <!-- Card Section -->
  <section class="container" style="padding-top: var(--spacing-xl); padding-bottom: var(--spacing-xl);">
    <div class="card">
      <div class="card-header">
        <span style="font-size: 2rem;">✨</span>
        <h2 class="card-title">卡片组件示例</h2>
      </div>
      <p class="card-description">
        这是一个使用 CSS Modules 构建的卡片组件，展示了设计变量的实际应用效果。
        所有颜色、间距、圆角和阴影都来自您的设计配置。
      </p>
    </div>
  </section>
</body>
</html>`;
}

/**
 * 生成 Hero Section 组件
 */
function generateHeroHTML(_tokens: DesignTokens): string {
  return `<!-- Hero Section Component -->
<section class="hero">
  <div class="container">
    <h1 class="hero-title">Hero 标题</h1>
    <p class="hero-subtitle">Hero 副标题，描述主要内容</p>
    <div class="hero-actions">
      <button class="button button-primary">主要操作</button>
      <button class="button button-secondary">次要操作</button>
    </div>
  </div>
</section>`;
}

/**
 * 生成 Card 组件
 */
function generateCardHTML(_tokens: DesignTokens): string {
  return `<!-- Card Component -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">卡片标题</h3>
  </div>
  <p class="card-description">卡片描述内容，可以包含更多信息。</p>
</div>`;
}

/**
 * 生成 Button 组件
 */
function generateButtonHTML(_tokens: DesignTokens): string {
  return `<!-- Button Components -->
<div style="display: flex; gap: var(--spacing-md);">
  <!-- Primary Button -->
  <button class="button button-primary">主要按钮</button>

  <!-- Secondary Button -->
  <button class="button button-secondary">次要按钮</button>

  <!-- Disabled Button (add disabled attribute) -->
  <button class="button" disabled style="opacity: 0.5; cursor: not-allowed;">禁用按钮</button>
</div>`;
}
