/**
 * README Generator - 生成 README.md 文档
 * 为导出的设计系统生成使用说明
 */

import { type DesignTokens } from '@/stores/workspace-store';

/**
 * README 生成选项
 */
export interface ReadmeOptions {
  /** 风格名称 */
  styleName: string;
  /** 设计变量 */
  tokens: DesignTokens;
}

/**
 * 生成 README.md 文档
 * @param options - 生成选项
 * @returns 生成的 README 内容
 */
export function generateREADME(options: ReadmeOptions): string {
  const { styleName, tokens } = options;
  const date = new Date().toISOString().split('T')[0];

  return `# ${styleName} Design System

> 由 StyleSnap 生成 | ${date}

这个设计系统包含完整的 CSS 变量配置和组件样式，可直接集成到您的项目中。

## 📦 文件说明

| 文件 | 说明 |
|------|------|
| \`styles.css\` | CSS Variables 定义（\`:root {...}\`） |
| \`styles.module.css\` | CSS Modules 组件样式 |
| \`index.html\` | 完整 HTML 示例页面 |
| \`README.md\` | 本说明文档 |

## 🚀 快速开始

### 方式一：直接使用（推荐）

1. 将 \`styles.css\` 和 \`styles.module.css\` 复制到你的项目中
2. 在 HTML 中引入：
   \`\`\`html
   <link rel="stylesheet" href="styles.css">
   <link rel="stylesheet" href="styles.module.css">
   \`\`\`
3. 使用组件类名：
   \`\`\`html
   <button class="button button-primary">按钮</button>
   <div class="card">
     <div class="card-header">
       <h2 class="card-title">标题</h2>
     </div>
     <p class="card-description">描述文字</p>
   </div>
   \`\`\`

### 方式二：CSS Modules（React/Vue）

1. 将 \`styles.module.css\` 重命名为 \`DesignSystem.module.css\`
2. 在组件中导入：
   \`\`\`tsx
   import styles from './DesignSystem.module.css';

   function MyComponent() {
     return (
       <div className={styles.card}>
         <h2 className={styles['card-title']}>标题</h2>
       </div>
     );
   }
   \`\`\`

### 方式三：Tailwind CSS 集成

如需将设计变量转换为 Tailwind 配置，参考以下主题扩展：

\`\`\`js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        // ...
      },
      fontFamily: {
        heading: 'var(--font-heading)',
        body: 'var(--font-body)',
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        // ...
      },
    },
  },
};
\`\`\`

## 🎨 设计变量

### 配色方案

| 变量 | 值 | 用途 |
|------|-----|------|
| \`--color-primary\` | ${tokens.colorPalette.primary} | 主色调、按钮、链接 |
| \`--color-secondary\` | ${tokens.colorPalette.secondary} | 辅色、强调元素 |
| \`--color-background\` | ${tokens.colorPalette.background} | 页面背景 |
| \`--color-surface\` | ${tokens.colorPalette.surface} | 卡片、面板背景 |
| \`--color-text\` | ${tokens.colorPalette.text} | 主要文字 |
| \`--color-text-muted\` | ${tokens.colorPalette.textMuted} | 弱化文字 |
| \`--color-border\` | ${tokens.colorPalette.border} | 边框、分割线 |
| \`--color-accent\` | ${tokens.colorPalette.accent} | 强调色（hover、焦点） |

### 排版系统

| 变量 | 值 | 用途 |
|------|-----|------|
| \`--font-heading\` | ${tokens.fonts.heading} | 标题字体 |
| \`--font-body\` | ${tokens.fonts.body} | 正文字体 |
| \`--font-heading-weight\` | ${tokens.fonts.headingWeight} | 标题字重 |
| \`--font-body-weight\` | ${tokens.fonts.bodyWeight} | 正文字重 |
| \`--line-height-heading\` | ${tokens.fonts.headingLineHeight} | 标题行高 |
| \`--line-height-body\` | ${tokens.fonts.bodyLineHeight} | 正文行高 |

### 间距系统（基于 4px）

| 变量 | 值 | 用途 |
|------|-----|------|
| \`--spacing-xs\` | ${tokens.spacing.xs}px | 紧凑间距 |
| \`--spacing-sm\` | ${tokens.spacing.sm}px | 小间距 |
| \`--spacing-md\` | ${tokens.spacing.md}px | 中间距 |
| \`--spacing-lg\` | ${tokens.spacing.lg}px | 大间距 |
| \`--spacing-xl\` | ${tokens.spacing.xl}px | 超大间距 |

### 圆角配置

| 变量 | 值 | 用途 |
|------|-----|------|
| \`--radius-small\` | ${tokens.borderRadius.small} | 小按钮、标签 |
| \`--radius-medium\` | ${tokens.borderRadius.medium} | 卡片、输入框 |
| \`--radius-large\` | ${tokens.borderRadius.large} | 大容器、头像 |

### 阴影配置

| 变量 | 值 | 用途 |
|------|-----|------|
| \`--shadow-light\` | ${tokens.shadows.light} | 轻微悬浮效果 |
| \`--shadow-medium\` | ${tokens.shadows.medium} | 卡片、导航栏阴影 |
| \`--shadow-heavy\` | ${tokens.shadows.heavy} | 模态框、弹出层阴影 |

## 📱 响应式支持

所有组件样式均为响应式设计，自动适配移动端和桌面端。

## 🔧 定制建议

如需修改设计变量，编辑 \`styles.css\` 中的 \`root {...}\` 块即可。所有组件样式会自动继承新的变量值。

## 📄 License

本设计系统由 StyleSnap 生成，可自由用于商业和个人项目。

---

**Generated by [StyleSnap](https://stylesnap.dev)** - 前端开发者的设计系统生成工具
`;
}
