'use client';

import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { CodeBlock } from '@/components/code-block';
import { Copy, Download, FileCode, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';

interface StyleCodeViewerProps {
  styleId: string;
  styleName: string;
  codeCss?: string | null;
  codeHtml?: string | null;
  codeReact?: string | null;
  codeTailwind?: string | null;
}

/**
 * 风格代码查看器 - 用于风格详情页
 * 支持 Tabs 切换、单代码复制、ZIP 下载
 */
export function StyleCodeViewer({
  styleId,
  styleName,
  codeCss,
  codeHtml,
  codeReact,
  codeTailwind,
}: StyleCodeViewerProps) {
  const [open, setOpen] = useState(false);
  const [activeTab, setActiveTab] = useState('css');
  const [isDownloading, setIsDownloading] = useState(false);

  // 构建代码片段
  const codeSnippets = [
    {
      id: 'css',
      label: 'CSS Variables',
      language: 'css' as const,
      code: codeCss || '',
    },
    {
      id: 'html',
      label: 'HTML',
      language: 'html' as const,
      code: codeHtml || '',
    },
    {
      id: 'react',
      label: 'React',
      language: 'tsx' as const,
      code: codeReact || '',
    },
    {
      id: 'tailwind',
      label: 'Tailwind',
      language: 'javascript' as const,
      code: codeTailwind || '',
    },
  ].filter((s) => s.code && s.code.trim() !== '');

  // 获取当前代码
  const getCurrentCode = () => {
    const snippet = codeSnippets.find((s) => s.id === activeTab);
    return snippet?.code || '';
  };

  // 处理复制
  const handleCopy = async () => {
    const code = getCurrentCode();
    try {
      await navigator.clipboard.writeText(code);
      toast.success('代码已复制到剪贴板');
    } catch (error) {
      toast.error('复制失败');
    }
  };

  // 处理下载 ZIP
  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      // 动态导入 JSZip
      const JSZip = (await import('jszip')).default;
      const { saveAs } = await import('file-saver');

      const zip = new JSZip();

      // 添加所有代码文件到 ZIP
      codeSnippets.forEach((snippet) => {
        const extMap: Record<string, string> = {
          css: 'css',
          html: 'html',
          react: 'tsx',
          tailwind: 'js',
        };
        const filename = `style.${extMap[snippet.id]}`;
        zip.file(filename, snippet.code);
      });

      // 生成 README
      const readme = `# ${styleName}

由 StyleSnap 生成的设计系统代码

## 文件说明

${codeSnippets.map((s) => `- \`style.${s.id === 'css' ? 'css' : s.id === 'html' ? 'html' : s.id === 'react' ? 'tsx' : 'js'}\` - ${s.label}`).join('\n')}

## 使用方法

### CSS Variables

将 CSS 文件引入到你的项目中：

\`\`\`html
<link rel="stylesheet" href="style.css">
\`\`\`

然后在 HTML 中使用 CSS 变量：

\`\`\`css
.button {
  background: var(--color-primary);
  color: var(--color-text);
}
\`\`\`

### React

在 React 项目中导入：

\`\`\`tsx
import { HeroSection, Card } from './style';
\`\`\`

---

Generated by [StyleSnap](https://stylesnap.dev)
`;
      zip.file('README.md', readme);

      // 生成并下载 ZIP
      const blob = await zip.generateAsync({ type: 'blob' });
      const timestamp = new Date().toISOString().split('T')[0];
      const safeName = styleName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
      const filename = `stylesnap-${safeName}-${timestamp}.zip`;

      saveAs(blob, filename);
      toast.success('ZIP 下载已开始');
    } catch (error) {
      toast.error('下载失败：' + (error as Error).message);
    } finally {
      setIsDownloading(false);
    }
  };

  // 没有代码时显示提示
  if (codeSnippets.length === 0) {
    return (
      <div className="rounded-lg border bg-muted p-8 text-center">
        <FileCode className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
        <h3 className="text-lg font-medium">暂无代码</h3>
        <p className="text-muted-foreground mt-2">该风格暂未生成代码</p>
      </div>
    );
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="gap-2"
          onClick={() => setOpen(true)}
        >
          <FileCode className="h-4 w-4" />
          查看代码
          <ChevronRight className="h-3 w-3" />
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-5xl max-h-[85vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCode className="w-5 h-5" />
            导出代码 - {styleName}
          </DialogTitle>
        </DialogHeader>

        {/* ZIP 包内容清单 */}
        <div className="bg-muted/50 rounded-md p-3 text-sm">
          <p className="font-medium mb-2">📦 ZIP 包内容：</p>
          <ul className="grid grid-cols-2 gap-1 text-muted-foreground">
            {codeSnippets.map((s) => (
              <li key={s.id}>
                • style.{s.id === 'css' ? 'css' : s.id === 'html' ? 'html' : s.id === 'react' ? 'tsx' : 'js'} - {s.label}
              </li>
            ))}
            <li>• README.md - 使用说明</li>
          </ul>
        </div>

        <Tabs
          defaultValue={codeSnippets[0]?.id || 'css'}
          className="flex-1 overflow-hidden flex flex-col"
          onValueChange={setActiveTab}
        >
          <TabsList className="w-full justify-start overflow-x-auto">
            {codeSnippets.map((snippet) => (
              <TabsTrigger key={snippet.id} value={snippet.id}>
                {snippet.label}
              </TabsTrigger>
            ))}
          </TabsList>

          <div className="flex-1 overflow-auto mt-4">
            {codeSnippets.map((snippet) => (
              <TabsContent key={snippet.id} value={snippet.id}>
                <CodeBlock
                  code={snippet.code}
                  language={snippet.language}
                  showLineNumbers
                  maxHeight={500}
                />
              </TabsContent>
            ))}
          </div>
        </Tabs>

        <div className="flex justify-between gap-4 mt-6">
          <Button variant="outline" onClick={handleCopy}>
            <Copy className="w-4 h-4 mr-2" />
            复制当前代码
          </Button>
          <Button onClick={handleDownload} disabled={isDownloading}>
            <Download className="w-4 h-4 mr-2" />
            {isDownloading ? '生成中...' : '下载 ZIP'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
