/**
 * ZIP 文件生成工具
 * 使用 JSZip 生成代码包
 */

import JSZip from 'jszip'
import type { ZipFileOptions, ZipGeneratorOptions, ExportPackage } from '@/types/code-export'

/**
 * 创建 ZIP 文件
 */
export async function createZipFile(
  files: ZipFileOptions[],
  options: ZipGeneratorOptions = {}
): Promise<Blob> {
  const zip = new JSZip()
  const { includeReadme = true, readmeContent } = options

  // 添加 README 文件
  if (includeReadme) {
    zip.file(
      'README.md',
      readmeContent ||
        `# StyleSnap Export

这个压缩包包含从 StyleSnap 导出的设计变量和组件代码。

## 文件说明

- \`tokens.json\` - Design Tokens JSON 格式
- \`css/\` - 原生 CSS 代码
- \`tailwind/\` - Tailwind CSS 代码
- \`scss/\` - SCSS 代码
- \`css-in-js/\` - CSS-in-JS 代码 (Styled Components)

## 使用方式

### CSS

\`\`\`html
<link rel="stylesheet" href="css/styles.css">
\`\`\`

### Tailwind CSS

将 \`tailwind/config.js\` 内容复制到你的 \`tailwind.config.js\`

### SCSS

\`\`\`scss
@import 'scss/variables';
@import 'scss/mixins';
@import 'scss/components';
\`\`\`

### CSS-in-JS

\`\`\`jsx
import { Button, Card } from './css-in-js/components'
\`\`\`

---

Generated by StyleSnap
`
    )
  }

  // 添加各个文件
  files.forEach((file) => {
    const fullPath = file.path ? `${file.path}/${file.filename}` : file.filename
    zip.file(fullPath, file.content)
  })

  // 生成 Blob
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  })

  return blob
}

/**
 * 触发下载
 */
export function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * 生成导出包结构
 */
export function createExportPackageFiles(pkg: ExportPackage): ZipFileOptions[] {
  const files: ZipFileOptions[] = [
    // CSS
    { filename: 'variables.css', content: pkg.css.variables, path: 'css' },
    { filename: 'components.css', content: pkg.css.components, path: 'css' },

    // Tailwind
    { filename: 'config.js', content: pkg.tailwind.config, path: 'tailwind' },
    { filename: 'components.html', content: pkg.tailwind.components, path: 'tailwind' },

    // SCSS
    { filename: 'variables.scss', content: pkg.scss.variables, path: 'scss' },
    { filename: 'mixins.scss', content: pkg.scss.mixins, path: 'scss' },
    { filename: 'components.scss', content: pkg.scss.components, path: 'scss' },

    // CSS-in-JS
    { filename: 'tokens.js', content: pkg.cssInJs.tokens, path: 'css-in-js' },
    { filename: 'components.tsx', content: pkg.cssInJs.components, path: 'css-in-js' },

    // Tokens
    { filename: 'tokens.json', content: pkg.tokens.json },
    { filename: 'tokens.js', content: pkg.tokens.javascript },
    { filename: 'tokens.ts', content: pkg.tokens.typescript },
  ]

  return files
}
